### ISSUE TITLE
Kitchen redesign

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#11]

**Comment by crystal-lotus** [comment]
Follow up questions/issues for July 4th mtg:
MICROWAVE?!
location of wall sockets
holes in top of wood counter for cables
under cabinet lighting
under cabinet rod for hanging things and/or small shelves?
confirm faucet
confirm cabinet hardware
give dimensions of LPs for shelving
DW cabinet front or steel?
exhaust hood
final mat'l/color selection
confirm counter thickness

**Comment by crystal-lotus** [comment]
could be an alternative if all goes to hell w Innova

https://www.nolte-kitchens.com/en/haendlersuche

http://www.m-ruder.de/scripts/show.aspx?content=/core/kueche/partner/nolte&cmbAuswahl1=nolte&cmbAuswahl2=&cmbAuswahl3=&cmbAuswahl4=&cmbAuswahl5=&cmbAuswahl6=&Id=449&page=1#bereich

**Comment by gavin-norman-sociomantic** [comment]
Yeah, I think that's where the Clever One said he'll probably be working, from September.

**Comment by gavin-norman-sociomantic** [comment]
The Clever One recommended Ruder as another shop to ask at.

**Comment by crystal-lotus** [comment]
ok, we should make an appt. this week

Filiale Lichtenberg Kaskelkiez

Pfarrstr. 124, 10317 Berlin 
Tel: 030 - 55 77 26 15

Öffnungszeiten:
Mo. - Fr.: 10.00 bis 19.00 Uhr 
Sa.: 10.00 bis 18.00 Uhr und nach individueller Vereinbarung.

mehr zur Filiale Ostkreuz

**Comment by gavin-norman-sociomantic** [comment]
Done! Contract with Ruder in effect. (We can create new issues, if anything else to discuss comes up re: the kitchen.)

**Comment by crystal-lotus** [comment]
super duper
