### ISSUE TITLE
Choose light fittings

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#14]
- [x] Small bedroom -- bought from http://pierreguibert.tictail.com/
- [x] Main bedroom -- ordered from ikea
- [x] Bathroom ceiling X 2 -- Lambent orbs
- [x] Bathroom mirror -- https://www.designort.com/produkt/conik-wall/ (ordered from belbis.de)
- [x] Storage room -- Lambent orb
- [x] Shower room ceiling -- Lambent orb
- [x] Shower room mirror -- https://www.designort.com/produkt/conik-wall/ (ordered from belbis.de)

**Comment by crystal-lotus** [comment]
don't forget Modulor!

**Comment by crystal-lotus** [comment]
http://www.bruck.de/
http://www.bruck.de/de/service/kontakt/fachhaendler-finden/

eco track (silver?)
http://www.brucklighting.com/products/lights/track-cable-systems/eco

eco track head (silver?)
http://www.brucklighting.com/products/lights/fixture-heads/z10-led-track-spot-416-detail
http://www.brucklighting.com/products/lights/fixture-heads/chroma-15-detail

**Comment by crystal-lotus** [comment]
bathroom?

wall-mount
http://www.brucklighting.com/products/lights/sconce-ceiling/eclipse-2-sconce-detail
http://www.lichthausmoesch.de/decor-walther-spiegelleuchte-box.html
http://www.lichthausmoesch.de/decor-walther-wandleuchte-box.html

ceiling-mount
http://www.lichthausmoesch.de/decor-walther-deckenleuchte-fix.html
https://www.hoeffner.de/artikel/663339
https://www.hoeffner.de/artikel/663341
https://www.hoeffner.de/artikel/663631

**Comment by crystal-lotus** [comment]
master bedroom
https://www.hoeffner.de/artikel/10682642
https://www.hoeffner.de/artikel/10685864

**Comment by crystal-lotus** [comment]
for the bedside table
http://www.lichthausmoesch.de/tischleuchte-onfale-tavolo-piccolo.html

**Comment by gavin-norman-sociomantic** [comment]
Oligo 3-phase track system (240V):
http://www.oligo.de/oligo-public/de/product/Systemleuchten/230V-Phase/PH-A-LITTLE-BIT (chrome matt)

**Comment by gavin-norman-sociomantic** [comment]
Quote for the track system coming from Lichthaus Mösch. Bruck system.

**Comment by crystal-lotus** [comment]
this company makes track lighting in Berlin:

http://www.stratas.de/

**Comment by crystal-lotus** [comment]
seems to be some other options here for stores selling different systems:

http://www.archiexpo.com/distributor/berlin/led-track-light-70-23181.html

**Comment by gavin-norman-sociomantic** [comment]
Check out the price list (for STRATAS)... very expensive!

**Comment by crystal-lotus** [comment]
this looks like it could be interesting:

http://www.zumtobel.com/de-de/produkte/vivo.html?&GUID=37D3F7D3-2D84-43C9-96F7-BB43418D6BB2

Zumtobel Licht GmbH
Rotherstraße 16 10245 Berlin

**Comment by crystal-lotus** [comment]
and there are a range of things here:

http://www.deltalight.de/de/products/track

Piwarz
Dircksenstrasse 140-141, 10178 Berlin Germany

**Comment by gavin-norman-sociomantic** [comment]
Piwarz is where we were first. aka Mitte Licht. (They seem to go under several names... not sure why!)

**Comment by crystal-lotus** [comment]
I wondered about that! And they didn't mention this brand. Hmm.

They also have them here, but seems pretty deep west...
PREDIGER SHOWROOM BERLIN
HARDENBERGSTR. 20 10623 BERLIN 10

**Comment by gavin-norman-sociomantic** [comment]
So it sounds like the track system is pretty much sorted. I just did a calculation for a more optimised layout and came out about a hundred cheaper than what the guy at mitte licht suggested.

Apart from that, there are eight more lights we'll need:
- Small bedroom
- Main bedroom
- Bathroom ceiling X 2
- Bathroom mirror
- Storage room
- Shower room ceiling
- Shower room mirror

**Comment by crystal-lotus** [comment]
for the bedrooms

http://www.ikea.com/de/de/catalog/products/70311697/

http://www.ikea.com/de/de/catalog/products/50148565/

**Comment by gavin-norman-sociomantic** [comment]
http://pierreguibert.tictail.com/product/cardboard-lampshade-n3-type-a

**Comment by gavin-norman-sociomantic** [comment]
Done and ordered.
