### ISSUE TITLE
Find moving company

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#16]
They need to have a furniture lift thing, as we're not supposed to move furniture up the stair wells.

**Comment by crystal-lotus** [comment]
this is done, yes?

**Comment by gavin-norman-sociomantic** [comment]
Yes! The little ketchup men!

**Comment by gavin-norman-sociomantic** [comment]
See the % on Moving In increasing!
