### ISSUE TITLE
Get stuff out of basement

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#17]

**Comment by crystal-lotus** [comment]
need to coordinate w kai probably at least a week in advance. 

will this happen at the same time or before the move?

**Comment by gavin-norman-sociomantic** [comment]
I emailed Kai today asking about getting the stuff out.

**Comment by gavin-norman-sociomantic** [comment]
Arranged for the 12th. Time not set yet. (I suggested 18h.)

**Comment by gavin-norman-sociomantic** [comment]
Erledigt.
