### ISSUE TITLE
Get table from Inga

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#18]
It's probably easier if we get everything in one place, for the actual moving day.

**Comment by crystal-lotus** [comment]
when do we want to do this? should probably arrange w her soon (just cause her schedule is so busy) and find someone who can help (rent van, carry, etc.), Hans?? Would be best to just take it to the new flat I guess... your thoughts? (this is one example where cash is good to have?)

**Comment by gavin-norman-sociomantic** [comment]
Yeah good point (about the cash and the good to arrange soon). I'll ask Inga. I guess we can do it any time after the painting.

**Comment by crystal-lotus** [comment]
yuppers

**Comment by gavin-norman-sociomantic** [comment]
Totally done.
