### ISSUE TITLE
Find and order bed

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#19]

**Comment by gavin-norman-sociomantic** [comment]
Some ideas: https://www.haikudesigns.com/eco-beds.htm

**Comment by crystal-lotus** [comment]
http://www.holz-futon-werkstatt.de/

http://www.wohnwerk-berlin.com/products-page/betten

**Comment by crystal-lotus** [comment]
http://www.bettkonzept.de/massivholzbetten/designer-bett-pure.html

**Comment by crystal-lotus** [comment]
http://www.traumkonzept.com/standard/produkte/massivholzbetten-naturholzbetten/
http://www.traumkonzept.com/standard/produkte/massivholzbetten-naturholzbetten/betten-von-traumkonzept/doug/
http://www.traumkonzept.com/standard/produkte/massivholzbetten-naturholzbetten/zack/massivholzbett-night/

**Comment by crystal-lotus** [comment]
https://www.belama.de/mm-collection-massivholzbett-drevo.html

**Comment by gavin-norman-sociomantic** [comment]
Ooh the Traumkonzept one looks nice!

**Comment by crystal-lotus** [comment]
http://www.moebel-kraft.de/design-betten/
http://www.moebel-kraft.de/tempur/

**Comment by crystal-lotus** [comment]
http://www.exedra-berlin.de/kollektionen/ethnicraft-teak/teak-horizon/789/bett-ethnicraft-teak-azur?c=105

**Comment by crystal-lotus** [comment]
WE BOUGHT DOUG IN BUCHE! FANCY MATTRESS TO BOOT YO. DONE.

**Comment by gavin-norman-sociomantic** [comment]
Closing this issue. :tada:

**Comment by gavin-norman-sociomantic** [comment]
No delivery date set, but we can arrange one with about two weeks notice.
