### ISSUE TITLE
Kitchen design

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#2]

**Comment by gavin-norman-sociomantic** [comment]
The "design" and "modern" kitchens here look interesting:
http://www.kuechen-aktuell.de/design-kuechen.html

**Comment by gavin-norman-sociomantic** [comment]
Similar looking stuff:
http://www.berlin-kuechen.de/kuechen/kuechen-design/design-pur/

**Comment by gavin-norman-sociomantic** [comment]
There's a company called Warendorf who seem to have pretty swanky stuff! Their website seems to be down atm, though :(

**Comment by gavin-norman-sociomantic** [comment]
SieMatic showroom in Berlin: http://www.siematic-am-leipziger-platz.de/SieMatic_am_Leipziger_Platz_startseite.htm

**Comment by gavin-norman-sociomantic** [comment]
A couple of less fancy places:
https://www.hoeffner.de/berlin-wedding (Wedding)
http://www.moebel-huebner.de/produkte/essen/kuechen (Tiergarten)

**Comment by gavin-norman-sociomantic** [comment]
Mega design store: http://www.stilwerk.de/en/berlin/storefinder/

**Comment by crystal-lotus** [comment]
Been thinking about the overall look of the kitchen/ dining wall and how to integrate the two areas together conceptually... Like continuing the level of the countertop all the way across the wall  (to the window wall) as a shelf or something, so the kitchen doesn't feel like this isolated corner that has nothing to do with the rest of the room... Will try to find some images to support my idea...

**Comment by crystal-lotus** [comment]
Hmm, looking at these kitchens, I wonder if there's a way to integrate an exhaust hood for the stove top? Seems to be a question for Marco. I wonder if we need one? And if the stove/ oven was located in the countertop area that sticks out into the room, how might an exhaust solution work?

**Comment by crystal-lotus** [comment]
I'm liking the idea of the transom wall (masterbath on other side) just being for fridge and tall storage cabinets along the entire length, kind of monolithic; no countertop there. maybe nothing on the perpendicular wall that you see when you enter the flat and countertop coming out from that wall for the sink, dishwasher and stove facing the window wall (parallel to the monolith wall)... It could maybe be deep enough to have bar stools on the other side... I wonder if that would give us enough storage & work space? Just thinking out loud!

**Comment by gavin-norman-sociomantic** [comment]
Concrete kitchen design place in Berlin.

http://www.betonwerkstatt.com/projekte/kuechen/

The people sound really cool too -- lived in California, ecologically minded, Waldorf educated!

**Comment by gavin-norman-sociomantic** [comment]
We did it!

**Comment by crystal-lotus** [comment]
Yay!! It feels great to have accomplished so much and we did it together so easily!

--- Original Message ---
