### ISSUE TITLE
Find and set up internet provider

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#21]

**Comment by crystal-lotus** [comment]
remember how long it took at Kopenhagener Str. almost 6 weeks of messing around before it actually worked! we should try to schedule for the end of august when we get the keys, just in case!

**Comment by gavin-norman-sociomantic** [comment]
Good point. Something to get started with by mid-July, then (i.e. next week ;)

**Comment by crystal-lotus** [comment]
do you have any ideas on this or know of some? Inga had 02 maybe, whoever it was, they were garbage

**Comment by gavin-norman-sociomantic** [comment]
I'll ask the geeks at work ;)

**Comment by gavin-norman-sociomantic** [comment]
Nemanja recommends https://zuhauseplus.vodafone.de/internet-telefon/kabel/internet-phone-200-v.html and said that he got set up with them in a matter of days!

**Comment by crystal-lotus** [comment]
that is excellent!

**Comment by crystal-lotus** [comment]
this is done, yes?

**Comment by gavin-norman-sociomantic** [comment]
Yeah! Kabel Deutschland.
