### ISSUE TITLE
Sofa or Schlafsofa

### ISSUE THREAD

**Issue by crystal-lotus** [gavin-norman-sociomantic/the-crystal-sphere#25]

**Comment by crystal-lotus** [comment]
http://www.wohnwerk-berlin.com/products-page/schlafsofas

http://www.innovation-sofas-berlin.de/kollektionen.php

**Comment by crystal-lotus** [comment]
http://www.mysofabed.de/muenchen-deluxe-eckschlafsofa-mit-lattenrost-und-matratze_p2967.html

**Comment by crystal-lotus** [comment]
http://www.sofasinmotion.de/schlafsofas.php

**Comment by crystal-lotus** [comment]
shappy-chic!
https://www.hoeffner.de/artikel/19406270

**Comment by crystal-lotus** [comment]
http://www.moebel-kraft.de/polstermoebel/schlafsofa/

**Comment by crystal-lotus** [comment]
http://www.traumkonzept-berlin.de/produkte/schlafsofas-berlin/signet-schlafsofas-berlin/signet-sofa-blues-schlafsofa/
http://www.traumkonzept-berlin.de/produkte/schlafsofas-berlin/signet-schlafsofas-berlin/signet-sofa-salsa-relaxsofa/

**Comment by crystal-lotus** [comment]
Dennis. Design: Guido Rosati
Brunnenstraße 12
10119 Berlin
Mo-Fr 11-19 | Sa 11-18

http://www.betten-anthon.de/schlafsofas/milano/page/2/

http://www.sofasinmotion.de/milano-bedding-dennis.php

**Comment by crystal-lotus** [comment]
http://www.rahaus.de/sortiment/details/000380000701-wohnlandschaft-zerlegt-weston.html

**Comment by crystal-lotus** [comment]
Scandinavian Sofas 50% OFF BEFORE JULY 10!

https://www.bolia.com/en/products/01-102-37_6953123

https://www.bolia.com/de-de/mobel/sofas/modulsofas/#!/?Family=Element

https://www.bolia.com/de-de/mobel/sofas/modulsofas/#!/?Family=Angle

https://www.bolia.com/de-de/mobel/sofas/#!/?Family=Doze

**Comment by crystal-lotus** [comment]
getting a bit desperate

http://www.multipolster.de/sortiment/trends-modern-design

https://www.sitzfeldt.com/modulsofas

**Comment by gavin-norman-sociomantic** [comment]
Bought Scandinavia sofa from bolia. Delivery scheduled for September 3rd, but we can move it later if we want to. Give two weeks notice, if we want  change it.

**Comment by gavin-norman-sociomantic** [comment]
I just changed the delivery time to 8. September 2016 12:00-18:00, to coincide with the bed delivery. (Not sure how I'm going to work that day, but we'll cross that bridge when we come to it...)
