### ISSUE TITLE
sofa tisch

### ISSUE THREAD

**Issue by crystal-lotus** [gavin-norman-sociomantic/the-crystal-sphere#28]

**Comment by crystal-lotus** [comment]
http://www.exedra-berlin.de/kollektionen/ethnicraft-teak/teak-burger/809/sofatisch-teak-burger?c=222

http://www.exedra-berlin.de/kollektionen/ethnicraft-teak/teak-burger/805/tv-anrichte-teak-burger?c=105

http://www.exedra-berlin.de/kollektionen/finja-eiche/837/hocker-eiche-klotz?c=127

**Comment by crystal-lotus** [comment]
https://www.bolia.com/en/products/03-063-05_5021708#!/customize

**Comment by crystal-lotus** [comment]
guess we can close this as well

**Comment by gavin-norman-sociomantic** [comment]
Oh yeah! We got one :)
