### ISSUE TITLE
Fridge

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#3]
Ideas about what's important to look out for and specific models which look interesting.

**Comment by gavin-norman-sociomantic** [comment]
Energy efficiency aspects:
- **Energy rating.** How much energy the device uses.
- **Size.** Bigger fridges use more energy as they're cooling a larger volume.
- **Location.** Fridges should be placed so that they have sufficient ventilation and are not in the vicinity of other heat-producing appliances (like a cooker, say). Direct sunlight also has a heating effect.
- **Features.** A "no frost" feature makes the freezer function more efficiently.

(http://www.theguardian.com/lifeandstyle/2014/apr/30/eco-appliances-energy-saving-hints-fridges-freezers)

**Comment by gavin-norman-sociomantic** [comment]
A+++ seems to be the current highest energy rating.

**Comment by gavin-norman-sociomantic** [comment]
Eco Top Ten fridges:
http://www.ecotopten.de/grosse-haushaltsgeraete/kuehl-und-gefriergeraete

**Comment by gavin-norman-sociomantic** [comment]
Lots of good advice here: http://www.ecotopten.de/grosse-haushaltsgeraete/kuehl-und-gefriergeraete/kauftipps-fuer-kuehl-und-gefriegeraete

**Comment by gavin-norman-sociomantic** [comment]
A few places mention that separate fridge / freezer is more efficient than a combined device.

**Comment by gavin-norman-sociomantic** [comment]
Sounds like around 200 litre capacity is well enough.

**Comment by crystal-lotus** [comment]
Those fridges are crazy small! How 'bout something more _normal_ size?!

**Comment by gavin-norman-sociomantic** [comment]
This is the current top contender:
http://www.bosch-home.com/de/produkte/k%C3%BChlen-gefrieren/k%C3%BChl-gefrier-kombinationen/KGE49BI40.html

The facts:
- A+++ energy rating (the best)
- Super quiet
- Stainless ("noble") steel doors
- 201,0 cm x 70,0 cm x 65,0 cm (tall, wide, deep)
- 301L fridge space
- 111L freezer space

**Comment by gavin-norman-sociomantic** [comment]
Selected this at innova http://www.mediamarkt.de/de/product/_liebherr-cbpesf-4033-21-1877837.html?uympq=vpqr&rbtc=%7C%7C%7C%7Cp%7C%7C&gclid=Cj0KEQjw5Ie8BRCJ9fHlr_bH24cBEiQAkoDQcdJO3uUfQj152lzKP0QwFGXdnnKqDaDLiHk3YdGGNtMaArnK8P8HAQ
