### ISSUE TITLE
Give notice at current flat

### ISSUE THREAD

**Issue by crystal-lotus** [gavin-norman-sociomantic/the-crystal-sphere#30]
need to tell Kai 1 month before moving out?

**Comment by gavin-norman-sociomantic** [comment]
I believe it's one month, but we can check, just to make sure.

**Comment by crystal-lotus** [comment]
would we delay moving in if the kitchen isn't ready at the end of september (and have to get a temp sink & counter)? or worst case scenario, we don't even have the base cabinets?

**Comment by gavin-norman-sociomantic** [comment]
Hm not sure. We'll have to consider our strategy. Whether we prefer to move in asap and live with some unfinished stuff or to stay conservatively in Rigaer str until everything is ready and _then_ give our month's notice.

**Comment by gavin-norman-sociomantic** [comment]
I emailed Kai today. (The last rent has gone out.)
