### ISSUE TITLE
Organise deliveries, including registering a space on the street

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#34]
We have:
- Kitchen
- Moving van
- Sofa

**Comment by crystal-lotus** [comment]
Let's include the dates here too.

**Painting** needs to happen first. Ideally between Monday, **September 5 - 9** (sometime in this week, best if earlier in the week, for 3 coats of paint.

**Kitchen** delivery on Monday, **September 12**

Sofa and bed delivery dates?? Best if after painting...

**Comment by crystal-lotus** [comment]
**Moving** is ideally on Saturday September 24 or Sunday the 25th?!

**Crystal Maze** on Wednesday the 28th.

(We have off from September 24th - October 2.)

**Comment by gavin-norman-sociomantic** [comment]
> Painting needs to happen first. Ideally between Monday, September 5 - 9 (sometime in this week, best if earlier in the week, for 3 coats of paint.

Why not the week of **August 29th - September 2nd**?

**Comment by crystal-lotus** [comment]
Just to keep things interesting, I have a major **deadline** on **September 9** (also my mom's b-day), so will probably have to work at some point that weekend also.

**Comment by crystal-lotus** [comment]
Why not the week of August 29th - September 2nd?

It could also be possible but maybe risky? What if you find something is wrong during the key hand-over and it needs fixing?

**Comment by crystal-lotus** [comment]
we know for sure that the moving people arrange official stuff like our spot on the street?

**Comment by gavin-norman-sociomantic** [comment]
Yeah, it was written on the contract and I specifically asked them about the official registration stuff.

**Comment by gavin-norman-sociomantic** [comment]
It doesn't really seem like it's necessary for anything except the moving truck.
