### ISSUE TITLE
Position of light switches & electrical outlets

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#6]
There's a fixed number of such things that we get "for free" per room. They just need to be marked on a plan and given to Marco.

**Comment by gavin-norman-sociomantic** [comment]
I presume the position of the light fittings on the ceiling will be included in this too.

**Comment by crystal-lotus** [comment]
What's the for free limit? This seems like something easiest to just talk through when I'm there... We need to find places that sell light fixtures too!

**Comment by gavin-norman-sociomantic** [comment]
Hm, not sure whether the actual fixtures need to be decided by June 25th. I didn't get that impression...

**Comment by crystal-lotus** [comment]
Even if the specific fixtures are selected, we still need to know what type is going where so the get the proper wiring in place...

**Comment by crystal-lotus** [comment]
here's some track fixtures by the german company bruck that i am considering spec-ing for various locations in the flat, let me know what you think! trying to find a showroom where i could go look at the fixtures?

http://www.bruck.de/

http://www.brucklighting.com/products/lights/fixture-heads/z10-led-track-spot-416-detail

http://www.brucklighting.com/products/lights/pendants/z15-ledbay-400-detail

http://www.brucklighting.com/products/lights/track-cable-systems/eco/eco-track-detail

am trying to figure out where the track gets wired up, i think at one end or the other. the track is sold @ 4, 8 & 12 ft. lengths and can also be cut to length.

**Comment by gavin-norman-sociomantic** [comment]
> am trying to figure out where the track gets wired up, i think at one end or the other. the track is sold @ 4, 8 & 12 ft. lengths and can also be cut to length.

You don't think it's safe to assume it can be wired up in the middle, like the ones in the showroom?

**Comment by gavin-norman-sociomantic** [comment]
By the way, "Lichthaus" seems to be the phrase for such shops.

**Comment by crystal-lotus** [comment]
from the cut sheet it seems that it is wired at the end, not all track systems are the same... these would be mounted directly to the ceiling for a cleaner profile, not suspended like those in the showroom.
see "Eco power feeds"

http://www.brucklighting.com/cutsheets/Eco%20Track.pdf

these are LED fixtures btw
thanks!

**Comment by crystal-lotus** [comment]
when i google "Lichthaus Berlin" i don't get much...

**Comment by gavin-norman-sociomantic** [comment]
Err... I get loads:
http://www.lichthausmoesch.de/
http://lichthaus-wolle.de/
http://www.lichthaus-achterberg.de/
http://www.lichthaushuebner.de/

For example.

**Comment by gavin-norman-sociomantic** [comment]
We did it!
