### ISSUE TITLE
Bathroom storage

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [gavin-norman-sociomantic/the-crystal-sphere#8]
There's not much in the current plan. We'l need some!

**Comment by gavin-norman-sociomantic** [comment]
One idea (probably essential) would be to fit a cabinet underneath the sink.

This is the sink we chose: http://www.reuter.de/keramag-icon-waschtisch-b-120-t-485-cm-weiss-mit-keratect-mit-2-hahnloechern-a186810.php

![keramag-icon-waschtisch-b-120-t-485-cm-weiss-mit-keratect-mit-2-hahnloechern--ke-124020_0](https://cloud.githubusercontent.com/assets/2863963/7568631/16a5d590-f804-11e4-8ae1-9c81ec7447dc.jpg)

It says:

> Kombinierbar mit Waschtischunterschränken 840120, 840121, 840122, 840420, 840421 und 840422

(combinable with under-sink-cabinets 840120, 840121, 840122, 840420, 840421 und 840422)

Searching on that same website, I find these ones which look like they fit:
http://www.reuter.de/keramag-icon-waschtischunterschrank-b-119-h-62-t-477-cm-front-lava-matt-korpus-lava-matt-a475590.php

![keramag-icon-waschtischunterschrank-b-119-h-62-t-477-cm-front-lava-matt-korpus-lava-matt--ke-841421000_0](https://cloud.githubusercontent.com/assets/2863963/7568650/2d97a530-f804-11e4-9e42-72f00a165b2f.jpg)

http://www.reuter.de/keramag-waschtischunterschrank-b-118-h-494-t-473-cm-weiss-hochglanz-lack-a271570.php

![keramag-waschtischunterschrank-b-118-h-494-t-473-cm-weiss-hochglanz-lack--ke-860220000_0](https://cloud.githubusercontent.com/assets/2863963/7568662/3a23e412-f804-11e4-822d-1c36459eac21.jpg)

http://www.reuter.de/keramag-icon-waschtischunterschrank-b-119-h-24-t-477-cm-front-und-korpus-alpin-hochglanz-a49039.php

![keramag-icon-waschtischunterschrank-b-119-h-24-t-477-cm-front-und-korpus-alpin-hochglanz--ke-840120_0](https://cloud.githubusercontent.com/assets/2863963/7568672/48b91a92-f804-11e4-8af0-526abcacf1f3.jpg)

http://www.reuter.de/keramag-citterio-waschtischunterschrank-b-1184-h-554-t-504-cm-front-schwarz-korpus-graubraun-a370155.php

![keramag-citterio-waschtischunterschrank-b-1184-h-554-t-504-cm-front-schwarz-korpus-graubraun--ke-835121000_0](https://cloud.githubusercontent.com/assets/2863963/7568690/55f450c8-f804-11e4-8f28-53f6f3d92ce1.jpg)

One thing I notice is that this reuter website has all of these things massively reduced (like 60% off). If we were to arrange this in advance through Marco, I bet we'd pay the full price. It looks like these cabinets can be retro-fitted, so it may be worth just getting one ourselves and doing it after moving in.

**Comment by gavin-norman-sociomantic** [comment]
> One thing I notice is that this reuter website has all of these things massively reduced (like 60% off). If we were to arrange this in advance through Marco, I bet we'd pay the full price. It looks like these cabinets can be retro-fitted, so it may be worth just getting one ourselves and doing it after moving in.

Yeah. For example, they have charged me 1598.10€ for that sink, which is listed on retuer.de as 1044.82€ reduced to 406.49€!

**Comment by crystal-lotus** [comment]
I like the white one, second from the top that presumably sits on the floor? :)

**Comment by gavin-norman-sociomantic** [comment]
> presumably sits on the floor

Hm, interesting point... I guess the exact height of the sink is flexible. The height (Höhe) of that cabinet is 49.4cm, so I'm not sure whether it'd sit on the floor or not. For example, I just measured the height of the sink in my bathroom here and it was 65cm off the floor.

It's also worth noting that the last sink is actually the largest at 55.4cm high. (From the photo it looks smaller. Unless something is screwed with their information...?)

**Comment by crystal-lotus** [comment]
we should def consider this for the small bath too, please tell Marco. Same style and color.

**Comment by gavin-norman-sociomantic** [comment]
I've just emailed Marco asking for  http://www.reuter.de/keramag-icon-waschtischunterschrank-b-119-h-62-t-477-cm-front-lava-matt-korpus-lava-matt-a475590.php (matt white) and asking if there's a matching one for the smaller sink in the shower room.

**Comment by crystal-lotus** [comment]
Excellent!

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by gavin-norman-sociomantic** [comment]
We chose these ones:

http://www.keramag.de/produkte/mobel/waschtischunterschranke/icon-waschtischunterschrank-595-x-620-x-477-mm-mit-schublade-und-auszug-griffe-verchromt-alpin-matt/16051/

http://www.keramag.de/produkte/mobel/waschtischunterschranke/icon-waschtischunterschrank-1190-x-620-x-477-mm-mit-2-schubladen-und-2-auszugen-griffe-verchromt-alpin-matt/16060/

Closing this issue :)
